### ISSUE TITLE
Begin Testing with Python 3.11 and 3.12 for all libraries we maintain

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#1045]
For all the repos we maintain that are python libraries, we need to update CI so that we are passing tests on Python 3.11 and 3.12 or identify any blockers that prevent us from passing tests in those versions.

```[tasklist]
### Repos
- [ ] https://github.com/openedx/axim-engineering/issues/1056
- [ ] https://github.com/openedx/XBlock/issues/719
- [ ] https://github.com/openedx/axim-engineering/issues/1053
- [ ] https://github.com/openedx/DoneXBlock/issues/208
- [ ] https://github.com/openedx/axim-engineering/issues/1049
- [ ] https://github.com/openedx/axim-engineering/issues/1051
- [ ] https://github.com/openedx/axim-engineering/issues/1059
- [ ] https://github.com/openedx/axim-engineering/issues/1052
- [ ] https://github.com/openedx/axim-engineering/issues/1050
- [ ] https://github.com/openedx/axim-engineering/issues/1055
```

## Acceptance Criteria

* All repos listed above, run test on Python 3.11 and 3.12
* Any blockers that prevent tests from passing are either fixed or tickets are created to address them.

## Other Info

* Example PR in a different repo: https://github.com/openedx/auth-backends/pull/297
```[tasklist]
### Tasks
```

**Comment by salman2013** [comment]
PR links:

**openedx-learning**
https://github.com/openedx/openedx-learning/pull/163

**event-bus-redis**
https://github.com/openedx/event-bus-redis/pull/81

**DoneXblock**
https://github.com/openedx/DoneXBlock/pull/207

**Comment by farhan** [comment]
PR links:

https://github.com/openedx/FeedbackXBlock/pull/61
https://github.com/openedx/xblock-in-video-quiz/pull/171
https://github.com/openedx/xblock-sdk/pull/352
https://github.com/openedx/opaque-keys/pull/288

**Comment by irtazaakram** [comment]
PR link:
https://github.com/openedx/edx-notes-api/pull/392
