### ISSUE TITLE
OEP-1: Updates for clarity & current realities

### ISSUE THREAD

**Issue by sarina** [openedx/axim-engineering#128]
## Problem

[OEP-1](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0001.html#updating-architecture-and-process-oeps) has lots of outdated information. Further, it's wordy and not very clear/approachable to new people coming on-board to their first written OEP or Arbitration role. @kdmccormick and @sarina are proposing a set of changes - they will write up changes individually and make separate PRs, requesting comment from the community on each.

## Tasks

- [ ] openedx/tcril-engineering#129 (in progress)
- [ ] openedx/tcril-engineering#130 (in progress)
- [ ] openedx/tcril-engineering#131 (in progress)
- [ ] openedx/tcril-engineering#132 (in progress)
- [ ] openedx/tcril-engineering#133 (blocked by 132)
- [ ] openedx/tcril-engineering#134 (in progress)
- [ ] openedx/tcril-engineering#135 (in progress)
- [x] openedx/open-edx-proposals#427
- [x] openedx/open-edx-proposals#428 
- [x] openedx/open-edx-proposals#429

**Comment by kdmccormick** [comment]
Thank you! 😄

**Comment by sarina** [comment]
I followed https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue to link my commits to my issues. My hope 🤞🏻 🤞🏻 🤞🏻 is that merging my PRs will automatically close my issue which will automatically tick the box next to the issue on _this_ issue.

**Comment by sarina** [comment]
Update: Merged in all my OEP-1 changes. When I next have downtime, I'll tackle #133
