### ISSUE TITLE
Micro-frontend replatforming (dependency deduplication, bundle splitting, performance optimization, module federation)

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/axim-engineering#437]
### Problem

A more common architecture would be to build a mono-framework that, with module federation, still gives the development flexibility we see now, but more tight integration with the overall platform.

### Product/Platform Value

Sometimes called "MFEs 3.0", this significant rewrite would solve many of the problems listed here in one go: however, it would be a break with the current architecture, so it is left for after the MFE conversion is completed.

### Acceptance Criteria

Needs discovery

### Related or in-progress work

```[tasklist]
- [x] #537
- [x] https://github.com/openedx/tcril-engineering/issues/529
- [ ] https://github.com/openedx/tcril-engineering/issues/633
- [ ] #542
- [ ] https://github.com/openedx/axim-engineering/issues/870
- [ ] https://github.com/aximcollaborative/funded-contributions/issues/53
```

### Contingencies

**Comment by arbrandes** [comment]
There is now a follow-on to the original discovery: [FC-0054](https://github.com/aximcollaborative/funded-contributions/issues/53).

**Comment by brian-smith-tcril** [comment]
@jmakowski1123 @arbrandes can I close this one now that the `frontend-base` work is being tracked elsewhere?

**Comment by arbrandes** [comment]
Yeah, we can close this.
