### ISSUE TITLE
Merge our Axim Eng onboarding docs

### ISSUE THREAD

**Issue by kdmccormick** [openedx/axim-engineering#795]
We have both:

* https://tcril-onboarding.readthedocs.io/en/latest/, built from https://github.com/aximcollaborative/axim-onboarding
* https://docs.google.com/document/d/1ya8WgQOlL5Nr6vT9-Ad5kr9WS7X4TEN-R46fnMUAxQU/edit

```[tasklist]
### Tasks
- [x] Choose one. WINNER: Google Doc.
- [ ] Update the Google Doc with any missing info from ReadTheDocs.
- [ ] Actually go through the onboarding process, and update the Google Doc with anything else that was missing.
- [ ] Delete the tcril-onboarding ReadTheDocs project.
- [ ] Archive the axim-onboarding source repo.
- [ ] Does there need to be any additional "offboarding" info in the doc? If so, add it.
```

**Comment by kdmccormick** [comment]
We chose to go with a Google Doc because:
* it's quicker to update, and the RTD has fallen out of date over time
* having all of our HR vendors out there is a little concerning

We acknowledge that this is a step away from openness.

**Comment by sarina** [comment]
Assigning to myself, will have the interns pick up on their first day.

**Comment by kdmccormick** [comment]
Closed in favor of https://github.com/aximcollaborative/axim-onboarding/issues/35
