### ISSUE TITLE
Update existing Axim Maintained Repositories

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#849]
The following repositories are currently maintained by the Axim Engineering Team.  They currently ping that team or members of that team for reviews on weekly maintenance PRs.

Goal: Update all the repos so that the @axim-aximprovements team gets tagged on new maintenance PRs instead.

## Task

* Update the review team to `@axim-aximprovements`
    * The files that need to be updated are the `.github/workflows/upgrade-python-requirements.yml` in each of the below repos.

### Relevant Repos
- [ ] [DoneXBlock](https://backstage.openedx.org/catalog/default/component/DoneXBlock)
- [ ] [FeedbackXBlock](https://backstage.openedx.org/catalog/default/component/FeedbackXBlock)
- [ ] [openedx-learning](https://backstage.openedx.org/catalog/default/component/openedx-learning)
- [ ] [XBlock](https://backstage.openedx.org/catalog/default/component/XBlock)
- [ ] [xblock-in-video-quiz](https://backstage.openedx.org/catalog/default/component/xblock-in-video-quiz)
- [ ] [xblock-sdk](https://backstage.openedx.org/catalog/default/component/xblock-sdk)
- [ ] [xblock-utils](https://backstage.openedx.org/catalog/default/component/xblock-utils)

# Acceptance Criteria
Confirm that all repos are making automated PRs and tagging the team correctly. (You'll have to wait till the time in the cron.  It should be Midnight UTC between Sunday and Monday.)

**Comment by thezaeemaanwar** [comment]
@feanil There is no `.github/workflows/upgrade-python-requirements.yml` in [openedx-learning](https://backstage.openedx.org/catalog/default/component/openedx-learning) repository. Shall I create a new one?

**Comment by feanil** [comment]
@thezaeemaanwar you should be able to assign the ticket to yourself now.  If a repo is missing the `upgrade-python-requiremnets.yml` file and has python code, yes, please create the workflow.

@ormsbee tagging you in-case you weren't running regular updates on purpose.

**Comment by feanil** [comment]
Sounds good, @thezaeemaanwar lets make sure and add the upgrade job to `openedx-learning`.

**Comment by feanil** [comment]
@thezaeemaanwar if the PR is approved by someone on the team, that is sufficient for you to merge them anywhere that you have merge rights.  They do not need any extra approval.
