### ISSUE TITLE
Do Initial Maintenance for some Axim Repos

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#850]
Axim is taking on the maintenance for the following repositories.  As a part of taking this on, we need to perform the initial maintenance tasks as defined in our docs: https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html

## Tasks

* Do any initial tasks that have not yet been done as defined by the How-To

### Relevant Repos

- [ ] [tutor-contrib-aspects](https://github.com/openedx/tutor-contrib-aspects)
- [ ] [openedx-aspects](https://github.com/openedx/openedx-aspects)
- [x] [openedx-event-sink-clickhouse](https://github.com/openedx/openedx-event-sink-clickhouse)
- [x] [event-routing-backends](https://github.com/openedx/event-routing-backends)
- [ ] [aspects-dbt](https://github.com/openedx/aspects-dbt)
- [x] [xapi-db-load](https://github.com/openedx/xapi-db-load)
- [x] [opaque-keys](https://github.com/openedx/opaque-keys)

## Acceptance Criteria

* All initial maintenance has been complete.
* We've confirmed that all new repos are making automated PRs and correctly tagging the @axim-aximprovements team.

**Comment by salman2013** [comment]
@feanil Just for confirmation, in initial maintenance we need to do the first page maintenance things in https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html. ? although we also have ongoing maintainer tasks.

**Comment by salman2013** [comment]
@feanil For this [repository](https://github.com/openedx/openedx-aspects), as there is no python code file and there is no `.github/workflows/upgrade-python-requirements.yml` so how we will tag the reviewer?

**Comment by salman2013** [comment]
@feanil how can we find the owner of a package/component like 
`owner: "group:openedx-event-sink-clickhouse-maintainers"`
I discussed this with BOM squad they mentioned they have an internal document available for all this information, Can you confirm do we have the same sheet or any other document?

**Comment by feanil** [comment]
> @feanil Just for confirmation, in initial maintenance we need to do the first page maintenance things in https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html. ? although we also have ongoing maintainer tasks.

Correct, for the repositories listed, we'll want to do ongoing maintenance but we need to do all the initial work for them as well before the team can do the on-going maintenance going forward.



> @feanil For this [repository](https://github.com/openedx/openedx-aspects), as there is no python code file and there is no `.github/workflows/upgrade-python-requirements.yml` so how we will tag the reviewer?

For the openedx-aspects repo, since it doesn't have any python code, we don't need to setup python requirements updates for it now.  @bmtcril can you let us know if and when this has python requirements in the future if it should be managed by the Aximprovements team?


> @feanil how can we find the owner of a package/component like `owner: "group:openedx-event-sink-clickhouse-maintainers"` I discussed this with BOM squad they mentioned they have an internal document available for all this information, Can you confirm do we have the same sheet or any other document?

For any group in a catalog file, it refers to a github team,  so in this case the [openedx-event-sink-clickhouse-maintainers](https://github.com/orgs/openedx/teams/openedx-event-sink-clickhouse-maintainers) github team.

**Comment by bmtcril** [comment]
Yep, that repo is just housing docs and cross-repository issues for the project so shouldn't need anything.

**Comment by salman2013** [comment]
@feanil The repo like [tutor-contrib-aspects](https://github.com/openedx/tutor-contrib-aspects) which already has done initial maintenance but the owner in `catalog.yaml `file is not axim so should i update that? like following like 
`owner: group:openedx/cc-analytics`?
https://github.com/openedx/tutor-contrib-aspects/blob/d6d9d59912f3fdaf3954819935b3f6a5393e2596/catalog-info.yaml#L25

**Comment by feanil** [comment]
@salman2013 looking closer at this, I think it's fine to leave the owner as is.  I believe @bmtcril plans on managing these via the analytics CCs rather than the axim team directly.

**Comment by bmtcril** [comment]
Yeah whenever we get around to getting the github groups up to where we want them to be a few of those repos should be getting maintained by the analytics group.

**Comment by salman2013** [comment]
[tutor-contrib-aspects](https://github.com/openedx/tutor-contrib-aspects)
>> This repo has already covered all initial maintenance points

 [openedx-aspects](https://github.com/openedx/openedx-aspects)
>> This repo has already covered all initial maintenance points

 [openedx-event-sink-clickhouse](https://github.com/openedx/openedx-event-sink-clickhouse)
>> Done with it but don't have merging rights.

 [event-routing-backends](https://github.com/openedx/event-routing-backends)
>> Done with it but don't have merging rights.

 [aspects-dbt](https://github.com/openedx/aspects-dbt)
>> This repo has already covered all initial maintenance points

 [xapi-db-load](https://github.com/openedx/xapi-db-load)
>> Done and merged

 [opaque-keys](https://github.com/openedx/opaque-keys)
>> Done and merged

**Comment by bmtcril** [comment]
Thanks @salman2013 I've merged the openedx-event-sink-clickhouse PRs. Aximprovements should have wrtie on that repo, let me know if it's still an issue.

**Comment by feanil** [comment]
@salman2013 what's left for this ticket?

**Comment by salman2013** [comment]
@feanil This is the last PR which i have fixed but needs to merge from the owner side, otherwise, all things have been done.

https://github.com/openedx/event-routing-backends/pull/343

**Comment by feanil** [comment]
Awesome, I've just merged that one so this should be all set.
