### ISSUE TITLE
Remove Badges Code from edx-platform

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#852]
https://github.com/openedx/edx-platform/issues/31541 is an accepted deprecation of code in the edx-platform related to the old Badging infrastructure.

## Tasks

- [ ] Remove badging related code from edx-platform
- [ ] Update https://openedx.atlassian.net/wiki/spaces/COMM/pages/3726802953/Next+Release+Quince to inform people that the badging code has been removed.
    * Include any settings that are no longer relevant and can be removed from users config.
- [ ] Update [the DEPR ticket](https://github.com/openedx/edx-platform/issues/31541) once you have a PR.  Review internally then get a review by someone in [#wg-depr-slash-n-burn](https://openedx.slack.com/archives/CGB0S3L12) before merging.
- [ ] Coordinate merging the removal in [#cc-edx-platform](https://openedx.slack.com/archives/C02QN50TYMD)
    * You'll see examples of others doing the same in there.

## Acceptance Criteria
* All above work has been completed.
* The deprecation ticket has been linked to the relevant PR and merged.

**Comment by feanil** [comment]
@thezaeemaanwar https://openedx.atlassian.net/wiki/spaces/COMM/pages/1051361376/Removing+a+Djangoapp+from+an+existing+project might be helpful.

**Comment by thezaeemaanwar** [comment]
@feanil I'm unable to add PR in [the DEPR ticket](https://github.com/openedx/edx-platform/issues/31541)

**Comment by feanil** [comment]
I've linked them. You can also just add it as a comment in the future.

**Comment by BryanttV** [comment]
Hello!

I'm currently working with the Badging feature, and I would like an update on what would be the future of Badging on the platform, and if it is currently possible to configure it with credentials IDA. I would be very grateful to receive information about it.

Thank you!

**Comment by feanil** [comment]
@BryanttV the historic version of Badging has been removed from the platform as of last week.  It is still available in the latest Open edX releases (Palm and Quince) but will not be available in Redwood.  Currently I don't think we have any plans for a new badging implementation in the core platform.

**Comment by mariajgrimaldi** [comment]
Hi there, folks @BryanttV @feanil! In the Badges DEPR's ticket there's a mention of ongoing work in the credentials IDA. Do we have more info on it? Thanks!
