### ISSUE TITLE
Complete edx-user-state-client Deprecation

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#853]
https://github.com/openedx/public-engineering/issues/167 details the deprecation of a small repo that is a dependency of edx-platform.  The repo contains some code that needs to move to the `edx-platform` repo and then the repository can be archived.  See the DEPR for more info.

## Tasks

- [x] In an edx-platform PR
    - [x] Add the relevant code and tests from the edx-user-state-client repo.
    - [x] Remove the dependency on the edx-user-state-client repo
    - [x] Get the change reviewed by @ormsbee
- [x] Ensure the PR merges and is deployed to edx.org and not rolled back.
- [x] Follow the [Repo Archival Steps](https://docs.openedx.org/projects/openedx-proposals/en/latest/processes/oep-0014-proc-archive-repos.html#archive-steps) to archive the edx-user-state-client repo.

## Acceptance Criteria
* The edx-user-state-client repository is properly archived.

**Comment by salman2013** [comment]
@feanil for second point
`Remove the dependency on the edx-user-state-client repo`

I am wondering there are some packages which has `edx-user-state-client` as dependent packages, should i also remove them from the edx-platform?

https://github.com/openedx/edx-platform/blob/fb49c150a205d747f900ea38f32a930e85193123/requirements/edx/base.txt#L511
https://github.com/openedx/edx-platform/blob/fb49c150a205d747f900ea38f32a930e85193123/requirements/edx/base.txt#L553
https://github.com/openedx/edx-platform/blob/fb49c150a205d747f900ea38f32a930e85193123/requirements/edx/base.txt#L1207

**Comment by feanil** [comment]
@salman2013 I think you are reading that backwards.  Those are packages that are dependencies of edx-user-state-client.   See https://github.com/openedx/edx-user-state-client/blob/master/requirements/base.in for what I mean.

**Comment by feanil** [comment]
Since this was deployed via https://github.com/openedx/edx-platform/pull/33218 5 days ago and we haven't seen any issues, we can call this done.

**Comment by feanil** [comment]
Oh, wait, we still need to archive the original repo.  I'll re-open this until that's done.

**Comment by salman2013** [comment]
@feanil I think i don't have enough permission to access setting for this repository, i just need to do a last step to archive this repo from github. Could you please assign or guide me about permissions?
 
https://github.com/openedx/edx-user-state-client




![Image](https://github.com/openedx/axim-engineering/assets/4454296/3dbe3a01-38ec-4282-8369-96a26800ffc4)

**Comment by feanil** [comment]
The repo has been archived and moved.
