### ISSUE TITLE
Complete the bok-choy Deprecation

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#874]
The [bok-choy](https://github.com/openedx/bok-choy/) test framework has been [deprecated](https://github.com/openedx/public-engineering/issues/13) for quite some time but we have not yet completed the removal.  This ticket will track the remaining work left to complete the removal.

Note: Most of this is coming from  https://github.com/openedx/public-engineering/issues/13#issuecomment-1514797565

## Tasks

- [x] Ensure that bok_choy settings files (both .py and .yml) are no longer used in edx-platform. In general, production.py and minimal.yml should be suitable replacements.
- [x] Go through the remaining repos that install bok-choy(listed below): 
  * For each repo that installs bok-choy:
    * Is it deprecated?
      *  Yes -> Great, just make a note of that one this issue, and move on.
      * No -> Does it actually use bok-choy?
        * Yes -> Open an issue for removing bok-choy, [like this one](https://github.com/openedx/credentials/issues/1989).
        * No -> Open & merge a PR to remove bok-choy from the list of requirements.
- [x] Re-check to confirm that no other repos have added bok-choy as a dependency in the meantime.
- [ ] Create an axim-engineering request to archive both the [bok-choy](https://github.com/openedx/bok-choy/) and [edx-custom-a11y-rules repo](https://github.com/openedx/edx-custom-a11y-rules) which is used exclusively as a bok-choy add-on.
- [ ] Search for dangling references to bok-choy and remove them. For example, there are several obselete bok_choy settings files in edx-platform which can be removed.

## Acceptance Criteria

* edx-platform has no references of any sort to bok-choy
* All other repos that use bok-choy have an issue indicating that they need to upgrade.
* All teams that currently use bok-choy have been notified that bok-choy will be archived.
* The bok-choy and custom-a11y-rules repo have both been archived.

**Comment by salman2013** [comment]
Issues created to remove bok-choy usage

- https://github.com/openedx/xblock-drag-and-drop-v2/issues
- https://github.com/openedx/xblock-sdk/issues/319
- https://github.com/openedx/edx-analytics-dashboard/issues/1509
- https://github.com/openedx/xblock-utils/issues/233
- https://github.com/openedx/xblock-google-drive/issues/63
- https://github.com/openedx/edx-proctoring/issues/1156
- https://github.com/openedx/xblock-image-explorer/issues/106

**Comment by feanil** [comment]
@salman2013 I re-opened this ticket because we still haven't archived the repo and I found a few more repos that are still mentioning bok-choy and should have related tickets: https://github.com/search?q=org%3Aopenedx+bok-choy+language%3AText&type=code&l=Text

**Comment by feanil** [comment]
The repo has been archived now.
