### ISSUE TITLE
[Epic] Deprecate openedx.yaml

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#882]
```[tasklist]
### Tasks
- [ ] Create a deprecation ticket for openedx.yaml
- [ ] Update open-edx-proposals to remove openedx.yaml and use catalog-info.yaml for release information.
- [ ] https://github.com/openedx/repo-tools/issues/439
- [ ] Update all repos to move release data to catalog-info.yaml
- [ ] Remove openedx.yaml from all repos.
```

**Comment by brian-smith-tcril** [comment]
@feanil do we need to keep this open or can it be tracked by https://github.com/openedx/public-engineering/issues/349 alone now?
